FROM openjdk:latest
LABEL maintainer "vanwinkle.justin@gmail.com"

# Install everything needed to run an X app inside a container and more.
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
	curl \
        jq \
        chromium \
        git \
        libc6-dev \
        libgtk2.0-0 \
        libgtk-3-0 \
        libpango-1.0-0 \
        libcairo2 \
        libfontconfig1 \
        libgconf2-4 \
        libnss3 \
        libasound2 \
        libxtst6 \
        unzip \
        libglib2.0-bin \
        libcanberra-gtk-module \
        libgl1-mesa-glx \
        build-essential \
        gettext \
        libstdc++6 \
        software-properties-common \
        xterm \
        automake \
        libtool \
        autogen \
        libnotify-bin \
        aspell \
        aspell-en \
        htop \
        gvfs-bin \
        libxss1 \
        rxvt-unicode-256color \
        x11-xserver-utils \
        sudo \
        vim \
        xdg-utils \
        libgl1-mesa-dri \
        libcanberra-gtk-module \
        libexif-dev \
        pulseaudio && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and install, su-exec. https://github.com/ncopa/su-exec
# This is a simple tool that will simply execute a program with different privileges.
# The program will not run as a child, like su and sudo, so we work around TTY and signal issues.
RUN curl -fsSLR -o /usr/local/bin/su-exec \
    https://github.com/javabean/su-exec/releases/download/v0.2/su-exec.$(dpkg --print-architecture | awk -F- '{ print $NF }') && \
    chmod +x /usr/local/bin/su-exec

# Download and extract intellij
RUN cd /opt && \
    mkdir intellij && \
    cd intellij && \
    curl -L `echo -n \`curl -s 'https://data.services.jetbrains.com/products/releases?code=IIU&latest=true&type=eap' | jq -r '.IIU[0].downloads.linux.link'\`` | \
    tar xz && \
    mv ./*/* ./

# Setup our custom entry point which will use su-exec
# to run the requested command as the host's user.
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]