FROM justinvanwinkle/dev-base:latest
LABEL maintainer "vanwinkle.justin@gmail.com"

# Download and extract intellij
RUN cd /opt && \
    mkdir intellij && \
    cd intellij && \
    curl -L `echo -n \`curl -s 'https://data.services.jetbrains.com/products/releases?code=IIU&latest=true&type=eap' | jq -r '.IIU[0].downloads.linux.link'\`` | \
    tar xz && \
    mv ./*/* ./
