#!/usr/bin/env bash
self=$(readlink -f $0); tasks=`dirname ${self}`; projectRoot=`dirname ${tasks}`;
docker build -t justinvanwinkle/dev-intellij:latest -t justinvanwinkle/dev-intellij:`date +%Y%m%d` -f Dockerfile.dev-intellij $projectRoot;



